### ISSUE TITLE
Google Imagen do not save image after refresh page

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1816] opened 2024-07-23 16:57 UTC
### EPAM AI DIAL chat version

0.15.0

### How to reproduce

Steps:
1. create chat with Goole Imagen
2. add request -> model generate file -> generated very low ( more than 10 sec)
3. refresh page

### Actual result

Image is not displayed in chat, not in Manage attachments
in console error 413 Payload Too Large

![image (23)](https://github.com/user-attachments/assets/b6833857-0786-4fb3-8604-43a08a948b3c)

### Expected result

generated file should be dislayed in chat and in manage attachments modal

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment] 2024-07-24 09:11
issue is reproducible for gemini-pro-vision on review env

**Comment by VolhaBazhkova** [comment] 2024-08-20 09:09
Now the issue is not reproduced on staging env. It was fixed on BE.

**Closed as completed by VolhaBazhkova** 2024-08-20 09:09 UTC
Labels: bug
