### ISSUE TITLE
Overlay loses + button on certain scalling 

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-chat#1593] opened 2024-06-14 17:25 UTC
### EPAM AI DIAL chat version

0.13.0-rc

### What happened?

![image](https://github.com/epam/ai-dial-chat/assets/13064745/8feac14c-f6d8-4bd3-9efa-da143e9a0194)

Looks overlay embedded in QG for details 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment] 2024-07-09 14:05
The ticket is a duplicate of #1682

**Closed as completed by VolhaBazhkova** 2024-07-09 14:05 UTC
Labels: bug
