### ISSUE TITLE
[Import] Change import target path for the attachments.

### ISSUE THREAD

**Issue by denys-kolomiitsev** [epam/ai-dial-chat#1420] opened 2024-05-24 10:02 UTC
### Description

Now all imported attachments go to the `import/<conversation name>` folder.
It's need to be changed that attachments will go to the same folder from where they were exported.

### Related issues

- #1239 
- #1237

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment] 2024-06-04 15:26
The ticket was verified on staging successfully. Note that there is https://github.com/epam/ai-dial-chat/issues/1453 , so, user has to refresh the browser to see the created with postfix file in Manage attachments

Also seems that #1420 is a duplicate of #1239

**Closed as completed by VolhaBazhkova** 2024-06-04 15:26 UTC
Labels: enhancement
