### ISSUE TITLE
Fix(chat): Custom applications: ApplicationService

### ISSUE THREAD

**Issue by Derikyan** [epam/ai-dial-chat#1942] opened 2024-08-20 03:01 UTC
### Description

Refactor ApplicationService so that it uses storage as is done for convarsation and prompt services

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment] 2024-09-04 12:08
duplicate of https://github.com/epam/ai-dial-chat/issues/1955

**Closed as completed by IlyaBondar** 2024-09-04 12:08 UTC
Labels: enhancement
